services:
  backend:
    volumes:
      - ./:/app
      - /app/packages/backend/dist
      - /app/packages/canvas-lti-model/dist
      - /app/packages/frontend/dist
      - /app/packages/lti-model/dist
      - /app/packages/endpoint-ts/dist
      - /app/packages/model/dist
      - /app/result

  frontend:
    volumes:
      - ./:/app
      - /app/packages/backend/dist
      - /app/packages/canvas-lti-model/dist
      - /app/packages/frontend/dist
      - /app/packages/lti-model/dist
      - /app/packages/endpoint-ts/dist
      - /app/packages/model/dist
      - /app/result
