services:
  redis:
    image: redis:7.2.1
    expose:
      - "6379"
  db:
    build: ./docker/db
    environment:
      - POSTGRES_USER=yaltt
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=yaltt
