services:
  backend:
    labels:
      - traefik.enable=true
    environment:
      - YALTT_HOST=yaltt.inseng.test

  frontend:
    labels:
      - traefik.enable=true
      - "traefik.http.routers.yalttfrontend.rule=Host(`yaltt.inseng.test`)"
    networks:
      default:
        aliases:
          - yaltt.inst.test

networks:
  default:
    external: true
    name: "inst_shared"
