const canvasPrefix = <K extends string>(k: K) =>
  `https://canvas.instructure.com/lti/${k}` as const;

export const CanvasPlacementTypes = {
  AccountNavigation: canvasPrefix("account_navigation"),
  SimilarityDetection: canvasPrefix("similarity_detection"),
  AssignmentEdit: canvasPrefix("assignment_edit"),
  AssignmentGroupMenu: canvasPrefix("assignment_group_menu"),
  AssignmentIndexMenu: canvasPrefix("assignment_index_menu"),
  AssignmentMenu: canvasPrefix("assignment_menu"),
  AssignmentSelection: canvasPrefix("assignment_selection"),
  AssignmentView: canvasPrefix("assignment_view"),
  Collaboration: canvasPrefix("collaboration"),
  ConferenceSelection: canvasPrefix("conference_selection"),
  CourseAssignmentsMenu: canvasPrefix("course_assignments_menu"),
  CourseHomeSubNavigation: canvasPrefix("course_home_sub_navigation"),
  CourseNavigation: canvasPrefix("course_navigation"),
  CourseSettingsSubNavigation: canvasPrefix("course_settings_sub_navigation"),
  DiscussionTopicMenu: canvasPrefix("discussion_topic_menu"),
  DiscussionTopicIndexMenu: canvasPrefix("discussion_topic_index_menu"),
  EditorButton: canvasPrefix("editor_button"),
  FileMenu: canvasPrefix("file_menu"),
  FileIndexMenu: canvasPrefix("file_index_menu"),
  GlobalNavigation: canvasPrefix("global_navigation"),
  HomeworkSubmission: canvasPrefix("homework_submission"),
  LinkSelection: canvasPrefix("link_selection"),
  MigrationSelection: canvasPrefix("migration_selection"),
  ModuleGroupMenu: canvasPrefix("module_group_menu"),
  ModuleIndexMenu: canvasPrefix("module_index_menu"),
  ModuleIndexMenuModal: canvasPrefix("module_index_menu_modal"),
  ModuleMenu: canvasPrefix("module_menu"),
  ModuleMenuModal: canvasPrefix("module_menu_modal"),
  PostGrades: canvasPrefix("post_grades"),
  QuizIndexMenu: canvasPrefix("quiz_index_menu"),
  QuizMenu: canvasPrefix("quiz_menu"),
  SubmissionTypeSelection: canvasPrefix("submission_type_selection"),
  StudentContextCard: canvasPrefix("student_context_card"),
  ToolConfiguration: canvasPrefix("tool_configuration"),
  TopNavigation: canvasPrefix("top_navigation"),
  UserNavigation: canvasPrefix("user_navigation"),
  WikiIndexMenu: canvasPrefix("wiki_index_menu"),
  WikiPageMenu: canvasPrefix("wiki_page_menu"),
} as const;

export type CanvasPlacementType =
  (typeof CanvasPlacementTypes)[keyof typeof CanvasPlacementTypes];
